version: '3.8'

services:
  data-modeler:
    build: .
    container_name: data-modeler
    volumes:
      - ./config:/app/config
      - ./datasets:/app/datasets
      - ./output:/app/output
    ports:
      - "7777:7777"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
