version: '4'

services:
  data-modeler:
    build: .
    container_name: data-modeler
    volumes:
      - ./config:/app/config
      - /studio/data:/app/datasets
      - ./output:/app/output
    ports:
      - "7777:7777"
    # depends_on:
    #   - starrocks  # Depend on StarRocks frontend instead of PostgreSQL

  # starrocks:
  #   image: starrocks/allin1-ubuntu:latest
  #   container_name: starrocks
  #   security_opt:
  #     - seccomp:unconfined
  #   ports:
  #     - "8030:8030"  # HTTP port for FE
  #     - "9020:9020"  # Edit log port for FE
  #     - "9030:9030"  # Query port for FE
  #     - "8040:8040"
    # volumes:
      #  - singleton_fe0_data:/opt/starrocks/fe/meta
      #  - singleton_be0_data:/opt/starrocks/be/storage

# volumes:
#   singleton_fe0_data:
#   singleton_be0_data:
