output_path: 'output'
pds_data_path: 'datasets'
db_host: '10.70.100.24'  # Use the service name of the StarRocks frontend from docker-compose.yml
db_user: 'root'          # Default user for StarRocks; adjust as necessary
db_password: 'C3gerbdi'  # Use a secure password as needed
db_port: '9030'
db_name: 'data_modeler'
help_desk_url: "https://dev05.overtech.id/"